import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import songs from '../data/spotify.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>TopTunes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          songs.map((s, index) => {
            return (
              <div >
                <>{s.Pos <= 100 ? <div key={index}>
                  <div>{s.Pos} rank</div>
                  <div>{s.Artist}</div>
                  <div>{s.Title}</div>
                  <div>{s.Wks} weeks</div>
                  <div>{s.Pk}</div>
                  <div>{s.Streams}</div>
                  <div>{s['Streams+']}</div>
                  <div>{s['(x?)']}</div>
                  <div>{s.Total}</div>
                </div> : <></>}</>
              </div>
            )
          })
        }
      </main>
    </>
  )
}
